### ISSUE TITLE
Count(*) , Sum() , avg() not working

### ISSUE THREAD

**Issue by sriharsha9992** [citusdata/postgres_vectorization_test#2]
Hi,

SELECT count(*) from cstore_table;
SELECT sum(int_value) from cstore_table;
SELECT avg(bigint_value) from cstore_table;

   For all the above mentioned queries , psql is killed and i get the following error

"The connection to the server was lost. Attempting reset: Failed"

Thanks,
Harsha

**Comment by metdos** [comment]
Thanks for taking the time to contact us. This project was an internship project and it is not fully supported at the time being.

Could you share your full schema and PostgreSQL version you run with me?

**Comment by sriharsha9992** [comment]
Hi,

Foreign Table cstore_table
{
id bigint,
sub_id integer,
name citext,
price bigint,
rt time
}

  I am using postgres 9.4 .

Thanks ,
Harsha

**Comment by metdos** [comment]
Hey @sriharsha9992,

Sorry for the late reply. This was our intern's project on PostgreSQL 9.3 and he tested it with beta versions of PostgreSQL 9.4 (PostgreSQL 9.4 is released after we released this project.) This issue is related with a header change in v9.4, and not work on it anymore.

Best,
Metin
